export const feedback = [
  {
    Timestamp: '15/05/2021 07:49:12',
    Email: 'verma.deepak1607@gmail.com',
    'Mentor Name': 'Deepak Verma',
    'Mentee Name': 'Quresh Lakdawala',
    'Internship Company Name': 'TechESpace',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      'Yes, submit a new assessment',
    'Assessment number': '10/05',
    'Please select the assessment type': 'Engineering',
    'Quality & testing: Writing code': 3,
    'Quality & testing: Testing': 2,
    'Debugging & observability: Debugging': 3,
    'Software design & architecture: Understanding Code': 3,
    'Software design & architecture: Software Architecture': 3,
    Security: 2,
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 2,
    'Incremental value delivery: Prioritisation, dependencies': 2,
    'Self-organization: Reliability, delivery accountability': 3,
    'Self-organization: Economic thinking': 2,
    'Feedback: Delivering Feedback': 3,
    'Feedback: Seeking and receiving feedback': 2,
    'Communication: Effective communication': 3,
    'Communication: Knowledge Sharing': 2,
    'Collaboration: Teamwork': 3,
    'Collaboration: Relationship building': 3,
    'Collaboration: Handling disagreement': 3,
    'Decision making': 3,
    'Driving alignment': 3,
    'Process thinking': 3,
    Mentoring: 3,
    'Business Acumen & Strategy: Business Acumen': 3,
    'Business Acumen & Strategy: Product Thinking': 3,
    'Additional evaluation comments':
      'He is bit confused about his role at present. Asked him to focus on the role and tasks given to him at present. Also to focus more on coding part only rather than playing role of Manager at this stage. He need to inculcate habit of reading blogs and books to keep him updated about latest trends.',
    'Is the mentee evolving his skills as planned?':
      'As mentioned above he does what is asked from him. e.ge he started to play role of team manager in his last organisation.',
    'Weekly mentoring remarks':
      'He is strong in technical part. Lacks in general aptitude. Also uncertain what he wants to achieve in short term and long term. Earning money seems to be a dire need for him, which makes sense but asked him to aim for Skills and Knowledge.\nGave him 4 pointers in last session\n- Focus on learning aspect, - Technology, Domain knowledge \n- Need to ensure that you don’t stroll away from your core strength \n- Start reading blogs\n- Keep yourself updated\n\nAlso, asked him to come up with answer of 2 Questions:\n1) What do you want to achieve in next 2 yrs - Short term goal\n2) What do you want to achieve in next 4-5 yrs - Long term goal',
    'Pain points of the mentee':
      'He is not clear in describing what he wants in life. More over he seems to get indulge in many things at a time rather than focusing on the required stuff.',
    'Would you like to submit a new forecast for the mentee?': 'Yes',
    'Technical Skills': 5,
    Delivery: 4,
    'Feedback, Communication, Collaboration': 4,
    Leadership: 3,
    'Strategic Impact': 4,
    'Forecast specific remarks':
      'Aim to this mentoring course would be to make Quresh :\n1) Able to understand the industry standards of coding and development.\n2) Inculcate the good engineering practices like Test Driven Development, unit test case writing, static code analysis, \n3) lowering the Cyclomatic complexity\n4) Understand the concept of Secure code guidelines.\n5) Understanding the process of task prioritisation and importance of understanding the company goal and succeed with the organisation.',
    'Would you submit new recommended courses for the mentee?': 'Yes',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'How to write unit tests in Django framework, https://docs.djangoproject.com/en/3.2/topics/testing/overview/, 20/05/2021\n\nPython static code analysis, https://www.sonarqube.org/features/multi-languages/python/, 20/05/2021\n\nUnit Testing and Test Driven Development in Python, https://www.udemy.com/course/unit-testing-and-tdd-in-python/, 25/05/2021',
    'How would you rate your mentee, mentoring-wise?': 4,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': 'Yes',
    'Is this the first session with this particular mentee?__1': 'Yes',
    'Is this the first session with this particular mentee?__2': 'Yes',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': ''
  },
  {
    Timestamp: '15/05/2021 18:33:03',
    Email: 'verma.deepak1607@gmail.com',
    'Mentor Name': 'Deepak Verma',
    'Mentee Name': 'Quresh Lakdawala',
    'Internship Company Name': 'TechESpace',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      'Yes, submit a new assessment',
    'Assessment number': '15/05',
    'Please select the assessment type': 'Engineering',
    'Quality & testing: Writing code': 3,
    'Quality & testing: Testing': 2,
    'Debugging & observability: Debugging': 4,
    'Software design & architecture: Understanding Code': 3,
    'Software design & architecture: Software Architecture': 3,
    Security: 2,
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 2,
    'Incremental value delivery: Prioritisation, dependencies': 2,
    'Self-organization: Reliability, delivery accountability': 4,
    'Self-organization: Economic thinking': 2,
    'Feedback: Delivering Feedback': 3,
    'Feedback: Seeking and receiving feedback': 2,
    'Communication: Effective communication': 3,
    'Communication: Knowledge Sharing': 2,
    'Collaboration: Teamwork': 3,
    'Collaboration: Relationship building': 3,
    'Collaboration: Handling disagreement': 3,
    'Decision making': 3,
    'Driving alignment': 3,
    'Process thinking': 3,
    Mentoring: 3,
    'Business Acumen & Strategy: Business Acumen': 3,
    'Business Acumen & Strategy: Product Thinking': 3,
    'Additional evaluation comments': '',
    'Is the mentee evolving his skills as planned?': 'Yes',
    'Weekly mentoring remarks':
      'Quresh was on time, had a great chat with him.',
    'Pain points of the mentee':
      'He has a notion of working with a well established company in the beginning itself but needs to work on his time management skills.\nWants to learn quick and a startup is good for it, but he should ensure that he spends the time required to understand every concept completely.',
    'Would you like to submit a new forecast for the mentee?': 'No',
    'Technical Skills': 5,
    Delivery: 4,
    'Feedback, Communication, Collaboration': 4,
    Leadership: 3,
    'Strategic Impact': 4,
    'Forecast specific remarks': '',
    'Would you submit new recommended courses for the mentee?': 'No',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'How to write unit tests in Django framework, https://docs.djangoproject.com/en/3.2/topics/testing/overview/, 20/05/2021\n\nPython static code analysis, https://www.sonarqube.org/features/multi-languages/python/, 20/05/2021\n\nUnit Testing and Test Driven Development in Python, https://www.udemy.com/course/unit-testing-and-tdd-in-python/, 25/05/2021',
    'How would you rate your mentee, mentoring-wise?': 5,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': 'No',
    'Is this the first session with this particular mentee?__1': 'No',
    'Is this the first session with this particular mentee?__2': 'No',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': ''
  },
  {
    Timestamp: '18/05/2021 16:12:36',
    Email: 'ksdeepti17@gmail.com',
    'Mentor Name': 'Deepti KS',
    'Mentee Name': 'Mauro Blanco',
    'Internship Company Name': 'Futuroid',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      '',
    'Assessment number': '18/05 - Week 1',
    'Please select the assessment type': 'Executive Assistant',
    'Quality & testing: Writing code': '',
    'Quality & testing: Testing': '',
    'Debugging & observability: Debugging': '',
    'Software design & architecture: Understanding Code': '',
    'Software design & architecture: Software Architecture': '',
    Security: '',
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 2,
    'Incremental value delivery: Prioritisation, dependencies': 2,
    'Self-organization: Reliability, delivery accountability': 4,
    'Self-organization: Economic thinking': 3,
    'Feedback: Delivering Feedback': 3,
    'Feedback: Seeking and receiving feedback': 4,
    'Communication: Effective communication': 5,
    'Communication: Knowledge Sharing': 4,
    'Collaboration: Teamwork': 4,
    'Collaboration: Relationship building': 5,
    'Collaboration: Handling disagreement': 3,
    'Decision making': 5,
    'Driving alignment': 3,
    'Process thinking': 4,
    Mentoring: 5,
    'Business Acumen & Strategy: Business Acumen': 4,
    'Business Acumen & Strategy: Product Thinking': 4,
    'Additional evaluation comments':
      'Mauro is a conscious professional who is on the path of self discovery to better his time management and networking skills, as per our first meeting. He is a pleasant person to talk to and has understanding about the role that he plays in his organization.',
    'Is the mentee evolving his skills as planned?': 'Yes',
    'Weekly mentoring remarks':
      'He asked 2 questions - one related to time management and the other related to building his LinkedIn presence.',
    'Pain points of the mentee':
      'He is having a hard time prioritizing tasks and differentiating between urgent and important tasks. He also wants to build his social media presence on LinkedIn.',
    'Would you like to submit a new forecast for the mentee?': '',
    'Technical Skills': 5,
    Delivery: 5,
    'Feedback, Communication, Collaboration': 5,
    Leadership: 4,
    'Strategic Impact': 4,
    'Forecast specific remarks':
      "Through the sessions, he'll definitely improve on his time management skills and ability to multitask. He is already very tech savvy.",
    'Would you submit new recommended courses for the mentee?': '',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'Eisenhower matrix, https://www.eisenhower.me/eisenhower-matrix/, 23/05/2021',
    'How would you rate your mentee, mentoring-wise?': 5,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': 'Yes',
    'Is this the first session with this particular mentee?__1': 'Yes',
    'Is this the first session with this particular mentee?__2': 'Yes',
    'Organisation: Time Management': 1,
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': 3,
    'Administration: Website Management': 3,
    'Organization: Documents Management (GDrive, etc)': 4,
    'Content Creation: Email Management': 3,
    'Administration: Agenda Coordination': 3
  },
  {
    Timestamp: '26/05/2021 05:47:27',
    'Email address': 'verma.deepak1607@gmail.com',
    'Mentor Name': 'Deepak Verma',
    'Mentee Name': 'Quresh Lakdawala',
    'Internship Company Name': 'TechESpace',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      'No, only submit a new forecast / amended courses',
    'Assessment number': '',
    'Please select the assessment type': '',
    'Quality & testing: Writing code': '',
    'Quality & testing: Testing': '',
    'Debugging & observability: Debugging': '',
    'Software design & architecture: Understanding Code': '',
    'Software design & architecture: Software Architecture': '',
    Security: '',
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': '',
    'Incremental value delivery: Prioritisation, dependencies': '',
    'Self-organization: Reliability, delivery accountability': '',
    'Self-organization: Economic thinking': '',
    'Feedback: Delivering Feedback': '',
    'Feedback: Seeking and receiving feedback': '',
    'Communication: Effective communication': '',
    'Communication: Knowledge Sharing': '',
    'Collaboration: Teamwork': '',
    'Collaboration: Relationship building': '',
    'Collaboration: Handling disagreement': '',
    'Decision making': '',
    'Driving alignment': '',
    'Process thinking': '',
    Mentoring: '',
    'Business Acumen & Strategy: Business Acumen': '',
    'Business Acumen & Strategy: Product Thinking': '',
    'Additional evaluation comments': '',
    'Is the mentee evolving his skills as planned?': '',
    'Weekly mentoring remarks': '',
    'Pain points of the mentee': '',
    'Would you like to submit a new forecast for the mentee?': 'No',
    'Technical Skills': '',
    Delivery: '',
    'Feedback, Communication, Collaboration': '',
    Leadership: '',
    'Strategic Impact': '',
    'Forecast specific remarks': '',
    'Would you submit new recommended courses for the mentee?': 'Yes',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'Project Estimation methodology, https://www.fullstacklabs.co/blog/estimate-deliver-software-project, 02/06/2021\n\nFunction Point Analysis in Detail, https://www.tutorialspoint.com/estimation_techniques/estimation_techniques_function_points.htm, 10/06/2021\n\nHow to write unit tests in Django framework, https://docs.djangoproject.com/en/3.2/topics/testing/overview/, 20/05/2021\n\nUnit Testing and Test Driven Development in Python, https://www.udemy.com/course/unit-testing-and-tdd-in-python/, 25/05/2021',
    'How would you rate your mentee, mentoring-wise?': 4,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': 'No',
    'Is this the first session with this particular mentee?__1': '',
    'Is this the first session with this particular mentee?__2': '',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': ''
  },
  {
    Timestamp: '27/05/2021 06:33:59',
    'Email address': 'verma.deepak1607@gmail.com',
    'Mentor Name': 'Deepak Verma',
    'Mentee Name': 'Quresh Lakdawala',
    'Internship Company Name': 'TechESpace',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      '',
    'Assessment number': '26/05 - Week 3',
    'Please select the assessment type': 'Engineering',
    'Quality & testing: Writing code': 3,
    'Quality & testing: Testing': 4,
    'Debugging & observability: Debugging': 4,
    'Software design & architecture: Understanding Code': 4,
    'Software design & architecture: Software Architecture': 3,
    Security: 3,
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 3,
    'Incremental value delivery: Prioritisation, dependencies': 3,
    'Self-organization: Reliability, delivery accountability': 4,
    'Self-organization: Economic thinking': 3,
    'Feedback: Delivering Feedback': 4,
    'Feedback: Seeking and receiving feedback': 4,
    'Communication: Effective communication': 4,
    'Communication: Knowledge Sharing': 3,
    'Collaboration: Teamwork': 3,
    'Collaboration: Relationship building': 3,
    'Collaboration: Handling disagreement': 3,
    'Decision making': 3,
    'Driving alignment': 3,
    'Process thinking': 3,
    Mentoring: 3,
    'Business Acumen & Strategy: Business Acumen': 4,
    'Business Acumen & Strategy: Product Thinking': 4,
    'Additional evaluation comments':
      'He is a good programmer and an individual contributor, that goes with his overall personality as well. As part of this mentoring program he is getting aware of industry standards of Engineering process as well. But it will depend on how fast he catches them and start including it in habit as well, then only it will show good results. Also, the organisation must provide him the environment to grow like someone senior to do his code reviews.',
    'Is the mentee evolving his skills as planned?': 'Yes',
    'Weekly mentoring remarks':
      'He is a good programmer and an individual contributor, that goes with his overall personality as well. \nAs part of this mentoring program he is getting aware of industry standards of Engineering process as well. \nBut it will depend on how fast he catches them and start including it in habit as well, then only it will show good results. \nAlso, the organisation must provide him the environment to grow like someone senior to do his code reviews.\n\nI like the part when he comes up with his questions during the sessions and that shows his willingness to learn. No doubt on that part that he want to learn and add new skills to him.\n\nHe also questions on need of things suggested to him. This is also positive, as this shows he is not the one who will adopt whatever the other person will say.\nBut at the same time he need to ensure that knowing more is right but doubting is not.\nFew things might look like overkill at his stage when he is just starting after college,\nhe need to keep in mind that these suggestions are being made mentor after a long industry experience.\n\nAs far as last session was concerned, we followed on the assignment that was given last time, i.e. writing test cases.\nHe had queries regarding why Test cases are important, and that was explained and he was agreeing that it serves a good purpose in engineering cycle.\n\nHe enquired about the project estimation techniques, and has been shared some articles about it.\n\nFor next session a target has been set to write test cases of his any project, I will check the test case execution and coverage report.\nI will also check how he is using the Sonar Lint plugin for static code analysis.',
    'Pain points of the mentee':
      'He is dealing with a cocktail of strong urge to deliver more and quickly and whether he should follow the process which seems ideal, may slow down him a bit in shorter span of time but will definitely make him more refined and his deliverable bug free.\n\nI hope that in some time he will realise the importance of these good practices and guidelines established in the industry.',
    'Would you like to submit a new forecast for the mentee?': 'No',
    'Technical Skills': 5,
    Delivery: 4,
    'Feedback, Communication, Collaboration': 4,
    Leadership: 3,
    'Strategic Impact': 4,
    'Forecast specific remarks': '',
    'Would you submit new recommended courses for the mentee?': 'Yes',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'How to write unit tests in Django framework, https://docs.djangoproject.com/en/3.2/topics/testing/overview/, 20/05/2021,green\n\nUnit Testing and Test Driven Development in Python, https://www.udemy.com/course/unit-testing-and-tdd-in-python/, 25/05/2021,green\n\nProject Estimation methodology, https://www.fullstacklabs.co/blog/estimate-deliver-software-project, 02/06/2021,grey\n\nFunction Point Analysis in Detail, https://www.tutorialspoint.com/estimation_techniques/estimation_techniques_function_points.htm, 10/06/2021,grey',
    'How would you rate your mentee, mentoring-wise?': 4,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': '',
    'Is this the first session with this particular mentee?__1': '',
    'Is this the first session with this particular mentee?__2': 'No',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': ''
  },
  {
    Timestamp: '09/06/2021 18:22:06',
    'Email address': 'puneetjindal@ameyo.com',
    'Mentor Name': 'Puneet Jindal',
    'Mentee Name': 'Mohamed Shamir',
    'Internship Company Name': 'Qurious Tech',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      '',
    'Assessment number': '06/06 - Week 1',
    'Please select the assessment type': 'Engineering',
    'Quality & testing: Writing code': 5,
    'Quality & testing: Testing': 5,
    'Debugging & observability: Debugging': 5,
    'Software design & architecture: Understanding Code': 3,
    'Software design & architecture: Software Architecture': 3,
    Security: 2,
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 3,
    'Incremental value delivery: Prioritisation, dependencies': 3,
    'Self-organization: Reliability, delivery accountability': 3,
    'Self-organization: Economic thinking': 2,
    'Feedback: Delivering Feedback': 4,
    'Feedback: Seeking and receiving feedback': 4,
    'Communication: Effective communication': 2,
    'Communication: Knowledge Sharing': 3,
    'Collaboration: Teamwork': 4,
    'Collaboration: Relationship building': 4,
    'Collaboration: Handling disagreement': 3,
    'Decision making': 2,
    'Driving alignment': 4,
    'Process thinking': 5,
    Mentoring: 4,
    'Business Acumen & Strategy: Business Acumen': 4,
    'Business Acumen & Strategy: Product Thinking': 4,
    'Additional evaluation comments': '',
    'Is the mentee evolving his skills as planned?': 'Yes',
    'Weekly mentoring remarks': 'db schema and decision making',
    'Pain points of the mentee': 'decision making and db',
    'Would you like to submit a new forecast for the mentee?': '',
    'Technical Skills': 4,
    Delivery: 4,
    'Feedback, Communication, Collaboration': 4,
    Leadership: 4,
    'Strategic Impact': 4,
    'Forecast specific remarks': '',
    'Would you submit new recommended courses for the mentee?': '',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'DB schema , API based query of DB Schema , validation of scale',
    'How would you rate your mentee, mentoring-wise?': 4,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': '',
    'Is this the first session with this particular mentee?__1': 'Yes',
    'Is this the first session with this particular mentee?__2': 'Yes',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': '',
    'Database usage': '',
    'Quality & testing: Writing code in React': '',
    'Knowledge about JavaScript': '',
    'HTML and CSS': '',
    'Quality & testing: Testing (unit, functional)': '',
    'Software design & architecture: Software Architecture__1': '',
    'Quality & testing: Writing code for Backend': '',
    'Data Analysis: Ability to analyze data and draw insights__2': '',
    'Content: Writing and editing skills__1': '',
    'Social Media Marketing: SEM and SEO campaigns__1': '',
    'Content: Videos and Podcasts': '',
    'Basic Design Skills: graphics': '',
    'Listening and CRM Skills__2': '',
    CSS: '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.__1':
      '',
    'Listening and CRM Skills__3': ''
  },
  {
    Timestamp: '11/06/2021 14:36:13',
    'Email address': 'verma.deepak1607@gmail.com',
    'Mentor Name': 'Deepak Verma',
    'Mentee Name': 'Quresh Lakdawala',
    'Internship Company Name': 'TechESpace',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      '',
    'Assessment number': '11/06 - Week 4',
    'Please select the assessment type': 'Engineering',
    'Quality & testing: Writing code': 4,
    'Quality & testing: Testing': 4,
    'Debugging & observability: Debugging': 4,
    'Software design & architecture: Understanding Code': 4,
    'Software design & architecture: Software Architecture': 4,
    Security: 4,
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 4,
    'Incremental value delivery: Prioritisation, dependencies': 4,
    'Self-organization: Reliability, delivery accountability': 4,
    'Self-organization: Economic thinking': 4,
    'Feedback: Delivering Feedback': 4,
    'Feedback: Seeking and receiving feedback': 4,
    'Communication: Effective communication': 5,
    'Communication: Knowledge Sharing': 3,
    'Collaboration: Teamwork': 4,
    'Collaboration: Relationship building': 4,
    'Collaboration: Handling disagreement': 4,
    'Decision making': 4,
    'Driving alignment': 4,
    'Process thinking': 4,
    Mentoring: 4,
    'Business Acumen & Strategy: Business Acumen': 4,
    'Business Acumen & Strategy: Product Thinking': 4,
    'Additional evaluation comments':
      'He is adapting to the suggestions being made and tools being recommended. Also he accepts that they have a positive impact on his working style.',
    'Is the mentee evolving his skills as planned?': 'Yes',
    'Weekly mentoring remarks':
      'Glad to see him understanding the importance of the suggestions being made to him.\nAs per him, static code analysis tool has helped him a lot in findings the areas where refactoring is required.\nHe has started to test his code as well.\nWe discussed about how to organise tasks and plan deliveries and little bit about the agile methodologies.\nThis will help him in better work management and tracking of deliveries.\nSuggested hi to adopt any tool for the same. e.g. Trello\n\nExplained him the evaluation process involved in this program.\nFor next session target is that he has to show case the test coverage of his code.\nProject estimation being a subjective and complex thing,  we have kept it on hold.\n\nWill move on to Security aspect in code in the next session.',
    'Pain points of the mentee':
      'The environment he is working in does not allow him much time to adopt the best practices.',
    'Would you like to submit a new forecast for the mentee?': 'Yes',
    'Technical Skills': 5,
    Delivery: 4,
    'Feedback, Communication, Collaboration': 4,
    Leadership: 4,
    'Strategic Impact': 4,
    'Forecast specific remarks':
      'After this program, he will evolve as a person who is more organised, managed in terms of his approach to code, estimate, deliver.\nHe will deliver quality releases, with less bugs and low complexity code.',
    'Would you submit new recommended courses for the mentee?': 'No',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'How to write unit tests in Django framework, https://docs.djangoproject.com/en/3.2/topics/testing/overview/, 20/05/2021,green\n\nUnit Testing and Test Driven Development in Python, https://www.udemy.com/course/unit-testing-and-tdd-in-python/, 25/05/2021,green\n\nProject Estimation methodology, https://www.fullstacklabs.co/blog/estimate-deliver-software-project, 02/06/2021,green\n\nFunction Point Analysis in Detail, https://www.tutorialspoint.com/estimation_techniques/estimation_techniques_function_points.htm, 10/06/2021,green',
    'How would you rate your mentee, mentoring-wise?': 5,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': '',
    'Is this the first session with this particular mentee?__1': 'No',
    'Is this the first session with this particular mentee?__2': 'No',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': '',
    'Database usage': '',
    'Quality & testing: Writing code in React': '',
    'Knowledge about JavaScript': '',
    'HTML and CSS': '',
    'Quality & testing: Testing (unit, functional)': '',
    'Software design & architecture: Software Architecture__1': '',
    'Quality & testing: Writing code for Backend': '',
    'Data Analysis: Ability to analyze data and draw insights__2': '',
    'Content: Writing and editing skills__1': '',
    'Social Media Marketing: SEM and SEO campaigns__1': '',
    'Content: Videos and Podcasts': '',
    'Basic Design Skills: graphics': '',
    'Listening and CRM Skills__2': '',
    CSS: '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.__1':
      '',
    'Listening and CRM Skills__3': ''
  },
  {
    Timestamp: '12/06/2021 04:46:18',
    'Email address': 'lalitalr@gmail.com',
    'Mentor Name': 'Lalit Goyal',
    'Mentee Name': 'Emil George Olaru',
    'Internship Company Name': 'futuroid',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      '',
    'Assessment number': '10/06- Week 1',
    'Please select the assessment type': 'Digital Marketing',
    'Quality & testing: Writing code': '',
    'Quality & testing: Testing': '',
    'Debugging & observability: Debugging': '',
    'Software design & architecture: Understanding Code': '',
    'Software design & architecture: Software Architecture': '',
    Security: '',
    'Data Analysis: Ability to analyze data and draw insights': 2,
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': 2,
    'Data Analysis: Ability to analyze data and draw insights__1': 2,
    'Content: Writing and editing skills': 2,
    'Social Media Marketing: SEM and SEO campaigns': 2,
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': 2,
    'Basic Design Skills: graphics design and videos': 2,
    'Listening and CRM Skills__1': 2,
    'Incremental value delivery: Work breakdown': 3,
    'Incremental value delivery: Prioritisation, dependencies': 3,
    'Self-organization: Reliability, delivery accountability': 2,
    'Self-organization: Economic thinking': 2,
    'Feedback: Delivering Feedback': 2,
    'Feedback: Seeking and receiving feedback': 2,
    'Communication: Effective communication': 3,
    'Communication: Knowledge Sharing': 3,
    'Collaboration: Teamwork': 3,
    'Collaboration: Relationship building': 3,
    'Collaboration: Handling disagreement': 3,
    'Decision making': 3,
    'Driving alignment': 3,
    'Process thinking': 3,
    Mentoring: 3,
    'Business Acumen & Strategy: Business Acumen': 3,
    'Business Acumen & Strategy: Product Thinking': 3,
    'Additional evaluation comments': 'He is new to digital marketing',
    'Is the mentee evolving his skills as planned?': 'Yes',
    'Weekly mentoring remarks':
      'He was clear on the job role & product he has to sell over social media channels',
    'Pain points of the mentee':
      'Targeting Customers & Developing content for them',
    'Would you like to submit a new forecast for the mentee?': '',
    'Technical Skills': 5,
    Delivery: 5,
    'Feedback, Communication, Collaboration': 4,
    Leadership: 4,
    'Strategic Impact': 4,
    'Forecast specific remarks':
      'marketing strategy is a area where he will become more better',
    'Would you submit new recommended courses for the mentee?': '',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'Digital Marketing Strategy,https://www.youtube.com/watch?v=sDoFp1vi4nY&t=184s,14/06/2021,grey',
    'How would you rate your mentee, mentoring-wise?': 3,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': '',
    'Is this the first session with this particular mentee?__1': 'Yes',
    'Is this the first session with this particular mentee?__2': 'Yes',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': '',
    'Database usage': '',
    'Quality & testing: Writing code in React': '',
    'Knowledge about JavaScript': '',
    'HTML and CSS': '',
    'Quality & testing: Testing (unit, functional)': '',
    'Software design & architecture: Software Architecture__1': '',
    'Quality & testing: Writing code for Backend': '',
    'Data Analysis: Ability to analyze data and draw insights__2': '',
    'Content: Writing and editing skills__1': '',
    'Social Media Marketing: SEM and SEO campaigns__1': '',
    'Content: Videos and Podcasts': '',
    'Basic Design Skills: graphics': '',
    'Listening and CRM Skills__2': '',
    CSS: '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.__1':
      '',
    'Listening and CRM Skills__3': ''
  },
  {
    Timestamp: '24/06/2021 05:22:05',
    'Email address': 'puneetjindal@ameyo.com',
    'Mentor Name': 'Puneet Jindal',
    'Mentee Name': 'Mohamed shamir',
    "Mentee's Company Name": 'Qurious tech',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      '',
    'Assessment number': '06/06 - Week-1',
    'Please select the assessment type': 'React and Backend',
    'Quality & testing: Writing code': '',
    'Quality & testing: Testing': '',
    'Debugging & observability: Debugging': '',
    'Software design & architecture: Understanding Code': '',
    'Software design & architecture: Software Architecture': '',
    Security: '',
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 3,
    'Incremental value delivery: Prioritisation, dependencies': 3,
    'Self-organization: Reliability, delivery accountability': 3,
    'Self-organization: Economic thinking': 2,
    'Feedback: Delivering Feedback': 3,
    'Feedback: Seeking and receiving feedback': 3,
    'Communication: Effective communication': 3,
    'Communication: Knowledge Sharing': 3,
    'Collaboration: Teamwork': 3,
    'Collaboration: Relationship building': 3,
    'Collaboration: Handling disagreement': 3,
    'Decision making': 3,
    'Driving alignment': 3,
    'Process thinking': 3,
    Mentoring: 3,
    'Business Acumen & Strategy: Business Acumen': 4,
    'Business Acumen & Strategy: Product Thinking': 3,
    'Additional evaluation comments': '',
    'Is the mentee evolving his skills as planned?': 'No',
    'Weekly mentoring remarks':
      'Need to work on basics of db creation and nodejs backend',
    'Pain points of the mentee': 'Lots of new domains',
    'Would you like to submit a new forecast for the mentee?': '',
    'Technical Skills': 3,
    Delivery: 3,
    'Feedback, Communication, Collaboration': 3,
    Leadership: 3,
    'Strategic Impact': 3,
    'Forecast specific remarks': '',
    'Would you submit new recommended courses for the mentee?': '',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'Express.js-Handling Routers and Controllers,https://youtu.be/04zWoxMg0WQ,-,grey',
    'How would you rate your mentee, mentoring-wise?': 3,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': '',
    'Is this the first session with this particular mentee?__1': 'Yes',
    'Is this the first session with this particular mentee?__2': 'Yes',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': '',
    'Database usage': 3,
    'Quality & testing: Writing code in React': 3,
    'Knowledge about JavaScript': 3,
    'HTML and CSS': 3,
    'Quality & testing: Testing (unit, functional)': 3,
    'Software design & architecture: Software Architecture__1': 3,
    'Quality & testing: Writing code for Backend': 3,
    'Data Analysis: Ability to analyze data and draw insights__2': '',
    'Content: Writing and editing skills__1': '',
    'Social Media Marketing: SEM and SEO campaigns__1': '',
    'Content: Videos and Podcasts': '',
    'Basic Design Skills: graphics': '',
    'Quality & testing: Writing code__1': '',
    'Quality & testing: Testing__1': '',
    'Debugging & observability: Debugging__1': '',
    'Software design & architecture: Understanding Code__1': '',
    'Software design & architecture: Software Architecture__2': '',
    'Knowledge about Typescript': '',
    Security__1: '',
    'Quality & testing: Writing code in NodeJs': '',
    'Database Usage': '',
    'Software design & architecture: Software Architecture__3': '',
    'Quality & Testing: Writing code in NodeJS': '',
    'Testing (unit, functional) & Debugging': '',
    'Database Usage__1': '',
    'Listening and CRM Skills__2': '',
    CSS: '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.__1':
      '',
    'Listening and CRM Skills__3': ''
  },
  {
    Timestamp: '24/06/2021 05:25:11',
    'Email address': 'puneetjindal@ameyo.com',
    'Mentor Name': 'Puneet Jindal',
    'Mentee Name': 'Mohamed shamir',
    "Mentee's Company Name": 'Qurious tech',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      '',
    'Assessment number': '12/06 - Week 2',
    'Please select the assessment type': 'React and Backend',
    'Quality & testing: Writing code': '',
    'Quality & testing: Testing': '',
    'Debugging & observability: Debugging': '',
    'Software design & architecture: Understanding Code': '',
    'Software design & architecture: Software Architecture': '',
    Security: '',
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 3,
    'Incremental value delivery: Prioritisation, dependencies': 3,
    'Self-organization: Reliability, delivery accountability': 3,
    'Self-organization: Economic thinking': 3,
    'Feedback: Delivering Feedback': 3,
    'Feedback: Seeking and receiving feedback': 3,
    'Communication: Effective communication': 3,
    'Communication: Knowledge Sharing': 3,
    'Collaboration: Teamwork': 3,
    'Collaboration: Relationship building': 3,
    'Collaboration: Handling disagreement': 3,
    'Decision making': 3,
    'Driving alignment': 3,
    'Process thinking': 3,
    Mentoring: 3,
    'Business Acumen & Strategy: Business Acumen': 3,
    'Business Acumen & Strategy: Product Thinking': 3,
    'Additional evaluation comments': '',
    'Is the mentee evolving his skills as planned?': 'No',
    'Weekly mentoring remarks':
      'Read nodejs and controller so that strapi is done , also read more on db',
    'Pain points of the mentee': 'Lots of new domains',
    'Would you like to submit a new forecast for the mentee?': 'No',
    'Technical Skills': 3,
    Delivery: 3,
    'Feedback, Communication, Collaboration': 3,
    Leadership: 3,
    'Strategic Impact': 3,
    'Forecast specific remarks': '',
    'Would you submit new recommended courses for the mentee?': 'No',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      '',
    'How would you rate your mentee, mentoring-wise?': 3,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': '',
    'Is this the first session with this particular mentee?__1': '',
    'Is this the first session with this particular mentee?__2': 'No',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': '',
    'Database usage': 3,
    'Quality & testing: Writing code in React': 3,
    'Knowledge about JavaScript': 3,
    'HTML and CSS': 3,
    'Quality & testing: Testing (unit, functional)': 3,
    'Software design & architecture: Software Architecture__1': 3,
    'Quality & testing: Writing code for Backend': 3,
    'Data Analysis: Ability to analyze data and draw insights__2': '',
    'Content: Writing and editing skills__1': '',
    'Social Media Marketing: SEM and SEO campaigns__1': '',
    'Content: Videos and Podcasts': '',
    'Basic Design Skills: graphics': '',
    'Quality & testing: Writing code__1': '',
    'Quality & testing: Testing__1': '',
    'Debugging & observability: Debugging__1': '',
    'Software design & architecture: Understanding Code__1': '',
    'Software design & architecture: Software Architecture__2': '',
    'Knowledge about Typescript': '',
    Security__1: '',
    'Quality & testing: Writing code in NodeJs': '',
    'Database Usage': '',
    'Software design & architecture: Software Architecture__3': '',
    'Quality & Testing: Writing code in NodeJS': '',
    'Testing (unit, functional) & Debugging': '',
    'Database Usage__1': '',
    'Listening and CRM Skills__2': '',
    CSS: '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.__1':
      '',
    'Listening and CRM Skills__3': ''
  },
  {
    Timestamp: '25/06/2021 07:17:06',
    'Email address': 'verma.deepak1607@gmail.com',
    'Mentor Name': 'Deepak Verma',
    'Mentee Name': 'Quresh Lakdawala',
    "Mentee's Company Name": 'TechESpace',
    'Would you like to submit a new assessment (with forecast) or only a forecast?':
      '',
    'Assessment number': 'Week 5',
    'Please select the assessment type': 'Engineering',
    'Quality & testing: Writing code': 4,
    'Quality & testing: Testing': 4,
    'Debugging & observability: Debugging': 5,
    'Software design & architecture: Understanding Code': 4,
    'Software design & architecture: Software Architecture': 4,
    Security: 4,
    'Data Analysis: Ability to analyze data and draw insights': '',
    'Content: Writing, drafting and editing skills': '',
    'Digital and Social Media Marketing: PPC, SEM and SEO campaigns': '',
    'Lead generation, follow-ups and convincing skills': '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.':
      '',
    'Listening and CRM Skills': '',
    'Data Analysis: Ability to analyze data and draw insights__1': '',
    'Content: Writing and editing skills': '',
    'Social Media Marketing: SEM and SEO campaigns': '',
    'Paid Campaigns and Email Marketing: PPC, EM, Advertising': '',
    'Basic Design Skills: graphics design and videos': '',
    'Listening and CRM Skills__1': '',
    'Incremental value delivery: Work breakdown': 4,
    'Incremental value delivery: Prioritisation, dependencies': 4,
    'Self-organization: Reliability, delivery accountability': 4,
    'Self-organization: Economic thinking': 4,
    'Feedback: Delivering Feedback': 4,
    'Feedback: Seeking and receiving feedback': 4,
    'Communication: Effective communication': 4,
    'Communication: Knowledge Sharing': 4,
    'Collaboration: Teamwork': 4,
    'Collaboration: Relationship building': 4,
    'Collaboration: Handling disagreement': 4,
    'Decision making': 4,
    'Driving alignment': 4,
    'Process thinking': 4,
    Mentoring: 4,
    'Business Acumen & Strategy: Business Acumen': 4,
    'Business Acumen & Strategy: Product Thinking': 4,
    'Additional evaluation comments': '',
    'Is the mentee evolving his skills as planned?': 'Yes',
    'Weekly mentoring remarks':
      'He is adopting the suggestions well and practicing them as well.\nWe have moved further to discuss the secure code guidelines now.\nIn Unit Testing we discussed that negative test cases should also be part of the test suite.\nWould like to see some examples in the next session.\n\nI am providing some links of curated guidelines of secure code practices.\nIt is an advanced topic, but even if one adopts some part of it, it improves his coding style and increases app security.',
    'Pain points of the mentee':
      'He has a lot of caliber, and can deliver a lot in good quality provided he is groomed well.',
    'Would you like to submit a new forecast for the mentee?': 'Yes',
    'Technical Skills': 4,
    Delivery: 5,
    'Feedback, Communication, Collaboration': 4,
    Leadership: 4,
    'Strategic Impact': 4,
    'Forecast specific remarks':
      'Once we complete this, he is gonna emerge as a much better programmer who not only just codes, but also groomed in the Engineering process to follow.\nOne who understands the best practices in the industry.\nOne who manages his work and deliveries well.\nIn all, a much desired person to be part of technical team to any organisation.',
    'Would you submit new recommended courses for the mentee?': 'Yes',
    'Please input the courses/tasks the mentee needs to complete in comma separated format (CSV)':
      'Secure coding practices, https://owasp.org/www-pdf-archive/OWASP_SCP_Quick_Reference_Guide_v2.pdf, 02/07/2021,grey\n\nSecure code practices, https://kirkpatrickprice.com/blog/secure-coding-best-practices/, 02/07/2021,grey',
    'How would you rate your mentee, mentoring-wise?': 5,
    "Once submitted, this assessment can't be amended": 'I agree',
    'Is this the first session with this particular mentee?': '',
    'Is this the first session with this particular mentee?__1': 'No',
    'Is this the first session with this particular mentee?__2': 'No',
    'Organisation: Time Management': '',
    'Content Creation: Office Suite (MS Word, Excel, Powerpoint)': '',
    'Administration: Website Management': '',
    'Organization: Documents Management (GDrive, etc)': '',
    'Content Creation: Email Management': '',
    'Administration: Agenda Coordination': '',
    'Database usage': '',
    'Quality & testing: Writing code in React': '',
    'Knowledge about JavaScript': '',
    'HTML and CSS': '',
    'Quality & testing: Testing (unit, functional)': '',
    'Software design & architecture: Software Architecture__1': '',
    'Quality & testing: Writing code for Backend': '',
    'Data Analysis: Ability to analyze data and draw insights__2': '',
    'Content: Writing and editing skills__1': '',
    'Social Media Marketing: SEM and SEO campaigns__1': '',
    'Content: Videos and Podcasts': '',
    'Basic Design Skills: graphics': '',
    'Quality & testing: Writing code__1': '',
    'Quality & testing: Testing__1': '',
    'Debugging & observability: Debugging__1': '',
    'Software design & architecture: Understanding Code__1': '',
    'Software design & architecture: Software Architecture__2': '',
    'Knowledge about Typescript': '',
    Security__1: '',
    'Quality & testing: Writing code in NodeJs': '',
    'Database Usage': '',
    'Software design & architecture: Software Architecture__3': '',
    'Quality & Testing: Writing code in NodeJS': '',
    'Testing (unit, functional) & Debugging': '',
    'Database Usage__1': '',
    'Listening and CRM Skills__2': '',
    CSS: '',
    'Knowledge of digital tools - Graphics creation, MailChimp, Hootsuite, Google Analytics, Facebook Analytics, Lead Generation, Presentation prep. etc.__1':
      '',
    'Listening and CRM Skills__3': ''
  }
];
